import { SignInButton, SignOutButton, useAuth } from "@clerk/nextjs";
import Head from "next/head";
import SearchForm from "~/components/searchForm";

export default function Home() {
  const { userId } = useAuth();

  return (
    <>
      <Head>
        <title>Comments-AI</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#19026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-3xl font-extrabold tracking-tight text-white sm:text-[3rem]">
            Comments-AI
          </h1>
          <div className="flex flex-col">
            { !!userId &&
              <div className="text-slate-200">
                <SignOutButton />
                <SearchForm  />
              </div>
            }
            { !userId &&
              <div className="text-slate-200">
                <SignInButton />
              </div>
            }
          </div>
        </div>
      </main>
    </>
  );
}