import { SignInButton, SignOutButton, useAuth } from "@clerk/nextjs";
import Head from "next/head";
import Link from "next/link";
import SearchForm from "~/components/searchForm";

export default function Home() {
  const { userId } = useAuth();

  return (
    <>
      <Head>
        <title>Comments-AI</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#f0f0f0] to-[#c8c8e6]">
          <nav className="w-screen flex justify-end">
            <div className="max-w-7xl mx-auto px-2 sm:px-6 lg:px-8">
              <div className="relative flex items-center justify-between h-16">
                <div className="flex-1 flex items-center justify-center sm:items-stretch sm:justify-start">
                  <div className="hidden sm:block sm:ml-6">
                    <div className="flex space-x-4">
                        { !userId &&
                          <div className="text-gray-600 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium">
                            <SignInButton />
                          </div>
                        }
                        { !!userId &&
                          <div className="text-gray-600 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium">
                            <SignOutButton />
                          </div>
                        }
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </nav>
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-12 ">
          <h1 className="text-3xl font-extrabold tracking-tight text-gray-400 sm:text-[3rem]">
            Comments-AI
          </h1>
          <div className="w-full flex content-end justify-end text-gray-600 flex-col">
            { !!userId &&
              <div className="text-gray-600">
                <SearchForm  />
              </div>
            }

          </div>
        </div>
      </main>
    </>
  );
}