import { SignInButton, SignOutButton, useAuth } from "@clerk/nextjs";
import Head from "next/head";
import SearchForm from "~/components/searchForm";
import Image from "next/image";
import Link from "next/link";

export default function Home() {
  const { userId, isLoaded } = useAuth();

  return (
    <>
      <Head>
        <title>Comments-AI</title>
        <meta name="description" content="Generated by create-t3-app"/>
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-col justify-between items-center w-full h-screen overflow-clip">
          <div className="absolute -z-50 bg-[url('/bg-GRADIENT.svg')] bg-no-repeat bg-cover h-full w-full "></div>
        
          { !userId && isLoaded &&
          <div className="container px-0 flex flex-col items-center h-full w-full max-w-4xl justify-center"> 
            <Image className="animate__animated animate__fadeInRight self-end w-96 md:w-144" src="/speech-help.png" width={508} height={199} alt="help teachers write"></Image>
            
            <h1 className="text-3xl flex items-center font-poppins font-semibold tracking-tight text-gray-800 sm:text-5xl p-3">
              comments-ai
            </h1>

            <SignInButton>
              <div className="w-64 h-12 rounded-full flex items-center justify-center border bg-gray-600 text-white border-gray-700 hover:text-violet-800 hover:fill-violet-800 hover:border-violet-800 hover:bg-violet-50 hover:shadow mb-3 cursor-pointer">
                Sign in
              </div>
            </SignInButton>

            <div className="flex flex-wrap w-full justify-between">
              <Image className="animate__animated animate__fadeInLeft animate__delay-2s a self-start w-72 md:w-96" src="/speech-candy.png" width={403} height={283} alt="student comment"></Image>
              <Image className="animate__animated animate__fadeInRight animate__delay-1s self-end w-64 md:w-96" src="/speech-andy.png" width={361} height={270} alt="student comment"></Image>              
            </div>
          </div>
          }

          {
            !userId && !isLoaded && 
            <svg className="stroke-gray-700 w-full h-8 mt-24" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24"><g fill="none" strokeLinecap="round" strokeWidth="2"><path strokeDasharray="60" strokeDashoffset="60" strokeOpacity=".3" d="M12 3C16.9706 3 21 7.02944 21 12C21 16.9706 16.9706 21 12 21C7.02944 21 3 16.9706 3 12C3 7.02944 7.02944 3 12 3Z"><animate fill="freeze" attributeName="stroke-dashoffset" dur="1.3s" values="60;0"/></path><path strokeDasharray="15" strokeDashoffset="15" d="M12 3C16.9706 3 21 7.02944 21 12"><animate fill="freeze" attributeName="stroke-dashoffset" dur="0.3s" values="15;0"/><animateTransform attributeName="transform" dur="1.5s" repeatCount="indefinite" type="rotate" values="0 12 12;360 12 12"/></path></g></svg>
          }

          { !!userId && 
            <>
              <div className="flex justify-between w-full max-w-4xl items-center">
                <h1 className="text-xl flex items-center font-poppins font-semibold tracking-tight text-gray-800 sm:text-3xl p-3">
                  comments-ai
                </h1>

                <nav className="flex items-center justify-between h-16">
                  <div className="flex items-center justify-center sm:items-stretch sm:justify-start">
                    <div className="sm:block sm:ml-6">
                      <div className="flex space-x-4 px-3 text-gray-600 text-sm font-medium">
                        <Link href="/user">
                          <div className="hover:text-violet-600 hover:fill-violet-600 hover:border-violet-400 hover:bg-violet-50 hover:shadow text-gray-600 fill-gray-600  border rounded-full font-semibold h-7 px-3 flex gap-2 items-center cursor-pointer">
                            <svg className="fill-inherit text-inherit w-4 h-4"  width="18" height="21" viewBox="0 0 18 21" fill="none" xmlns="http://www.w3.org/2000/svg">
                                <path className="fill-inherit text-inherit" d="M9 11C10.1935 11 11.3381 10.5259 12.182 9.68198C13.0259 8.83807 13.5 7.69347 13.5 6.5C13.5 5.30653 13.0259 4.16193 12.182 3.31802C11.3381 2.47411 10.1935 2 9 2C7.80653 2 6.66193 2.47411 5.81802 3.31802C4.97411 4.16193 4.5 5.30653 4.5 6.5C4.5 7.69347 4.97411 8.83807 5.81802 9.68198C6.66193 10.5259 7.80653 11 9 11ZM9 12.5C7.4087 12.5 5.88258 11.8679 4.75736 10.7426C3.63214 9.61742 3 8.0913 3 6.5C3 4.9087 3.63214 3.38258 4.75736 2.25736C5.88258 1.13214 7.4087 0.5 9 0.5C10.5913 0.5 12.1174 1.13214 13.2426 2.25736C14.3679 3.38258 15 4.9087 15 6.5C15 8.0913 14.3679 9.61742 13.2426 10.7426C12.1174 11.8679 10.5913 12.5 9 12.5ZM16.5 20V17.75C16.5 17.1533 16.2629 16.581 15.841 16.159C15.419 15.7371 14.8467 15.5 14.25 15.5H3.75C3.15326 15.5 2.58097 15.7371 2.15901 16.159C1.73705 16.581 1.5 17.1533 1.5 17.75V20C1.5 20.1989 1.42098 20.3897 1.28033 20.5303C1.13968 20.671 0.948912 20.75 0.75 20.75C0.551088 20.75 0.360322 20.671 0.21967 20.5303C0.0790178 20.3897 0 20.1989 0 20V17.75C0 16.7554 0.395088 15.8016 1.09835 15.0983C1.80161 14.3951 2.75544 14 3.75 14H14.25C15.2446 14 16.1984 14.3951 16.9016 15.0983C17.6049 15.8016 18 16.7554 18 17.75V20C18 20.1989 17.921 20.3897 17.7803 20.5303C17.6397 20.671 17.4489 20.75 17.25 20.75C17.0511 20.75 16.8603 20.671 16.7197 20.5303C16.579 20.3897 16.5 20.1989 16.5 20Z"/>
                            </svg>
                            User
                          </div>
                        </Link>
                      
                        <div className="hover:text-violet-600 hover:fill-violet-600 hover:border-violet-400 hover:bg-violet-50 hover:shadow text-gray-600 fill-gray-600 border rounded-full font-semibold h-7 px-3 flex items-center cursor-pointer">
                          <SignOutButton />
                        </div>
                      </div>
                    </div>
                  </div>
                </nav>
              </div>

              <div className="container flex flex-col items-center justify-center px-0 lg:px-4 py-3 ">
                <div className="bg-white bg-opacity-50 w-full flex justify-center rounded-2xl px-3 py-6 lg:p-6 max-w-4xl shadow-blue-under">
                  
                    <div className="text-gray-600">
                      <SearchForm  />
                    </div>
                  
                </div>
              </div>
            </>
          }
        <footer className="text-xs text-gray-500 p-3">
          {String.fromCharCode(169)+" "} abMakes 2023 
          {` `+ String.fromCharCode(183)} powered by openAI
        </footer>
      </main>
    </>
  );
}